![](NotebookHeader.jpg)

# Course                  : Python for Data Science

## Module 3 Lesson 1  : Numpy Arrays

In [4]:
marks = [20,30,40, 550, 600]

In [8]:
newmarks = marks*5

In [9]:
newmarks

[20,
 30,
 40,
 550,
 600,
 20,
 30,
 40,
 550,
 600,
 20,
 30,
 40,
 550,
 600,
 20,
 30,
 40,
 550,
 600,
 20,
 30,
 40,
 550,
 600]

### Create a numpy array object

In [1]:
import numpy as np

In [5]:
np_marks = numpy.array(marks)

In [12]:
np_marks

array([ 20,  30,  40, 550, 600])

### Vectorized Operations

In [13]:
np_marks*5

array([ 100,  150,  200, 2750, 3000])

In [14]:
np_marks.ndim

1

In [15]:
np_marks.shape

(5,)

### Two dimensional array

In [46]:
np_marks = np.array([[10,20,30], [100,200,300]], np.int32)

In [48]:
type(np_marks)
np_marks.shape

(2, 3)

In [49]:
np_marks[0]*2

array([20, 40, 60])

In [29]:
np_marks[1]

200

In [52]:
np_marks[1][2]

300

In [39]:
np_marks_2 = np_marks*2
np_marks_2

array([list([10, 200, 10, 200]), list([100, 200, 300, 100, 200, 300])],
      dtype=object)

In [21]:
np_marks = np.array(([10,20,30,40,50], [100,200, 300, 400, 500]))

In [53]:
np_marks

array([[ 10,  20,  30],
       [100, 200, 300]])

### Use of conditions for slicing / retriving subset

In [54]:
cond =  np_marks  > 20

In [59]:
np_marks[cond]

array([ 30, 100, 200, 300])

In [43]:
marks = [20,30,40, 550, 600]

In [44]:
np_marks = np.array(marks)

In [60]:
print(cond)

[[False False  True]
 [ True  True  True]]


In [48]:
cond2 = [True, False, True, False, True]

In [49]:
np_marks[cond2]

array([ 20,  40, 600])

### Applying statistical functions

In [62]:
marks = [20,30,40]
np_marks = np.array(marks)
np_marks.mean()

30.0

In [70]:
t1 = [10,20, 30]
t2 = [300,400,500]
t1 = np.array(t1)
t2 = np.array(t2)
print(t1)
print(t2)

[10 20 30]
[300 400 500]


### Combining two numpy arrays

In [66]:
np.concatenate([t1, t2])

array([ 10,  20, 300, 400, 500])

In [71]:
np.vstack([t1,t2])  

array([[ 10,  20,  30],
       [300, 400, 500]])

In [74]:
np.hstack([t1,t2])  

array([ 10,  20,  30, 300, 400, 500])

In [90]:
x = np.linspace(10, 20, 5)       # Generating five points (spaced equaly like on a number line) between 10 and 20
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [91]:
y = np.arange(10,20,2)
y

array([10, 12, 14, 16, 18])